annulus_end: 20
annulus_start: 12
aperture_radius: 5
calints_path: ./mast_lhs1478b
fit_exponential: false
fit_fnpca: true
fit_linear: true
perform_individual_fits: true
perform_joint_fit: false
planet_path: ./lhs1478b.yaml
skip_visits: null
star_position: null
trim_integrations:
- 10
- 40
