name: Regen schemas

on:
  push:
    paths:
      - src/utility/planet.py
      - src/utility/run_cfg.py
  workflow_dispatch:
  workflow_call:
permissions:
  contents: write
jobs:
  generate_schemas:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uncertainties
          pip install pydantic
          pip install pydantic_yaml
          pip install numpy

      - name: Run generate_schemas.py
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: python .github/workflows/generate_schemas.py
        
      - name: Commit and push changes
        run: |
          git config user.name "nicholasconnors"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Auto-generate schemas"
            git push origin HEAD:${{ github.ref_name }}
          else
            echo "No changes to schema"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
