name: Regen schemas

on:
  push:
    paths:
      - src/utility/planet.py
      - src/utility/run_cfg.py
  workflow_dispatch:
  workflow_call:
permissions:
  contents: write
jobs:
  generate_schemas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install setuptools
          pip install -r requirements.txt
      - name: Build release distributions
        run: |
          python -m pip install build
          python -m build
          cd dist
          pip install *.tar.gz
          cd ..

      - name: Run generate_schemas.py
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: python .github/workflows/generate_schemas.py
        
      - name: Commit and push changes
        run: |
          git config user.name "nicholasconnors"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Auto-generate schemas"
            git push origin HEAD:${{ github.ref_name }}
          else
            echo "No changes to schema"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
