name: Releases

on: 
  pull_request:
    types: 
      - synchronize
      - labeled
    branches:
      - main
jobs:
  build:
    uses: ./.github/workflows/build_package.yaml
  release:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/main' && contains(github.event.pull_request.labels.*.name, 'release') }}
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Get version from pyproject.toml
      uses: SebRollen/toml-action@v1.2.0
      id: get_version
      with:
        file: 'pyproject.toml'
        field: 'package.version'
    - name: Check if tag already exists
      uses: mukunku/tag-exists-action@v1.6.0
      id: check-tag
      with: 
        tag: ${{ github.event.pull_request.title }}
    - name: Check version match
      run: |
        if [[ "${{ steps.get_version.outputs.value }}" != "${{ github.event.pull_request.title }}" ]]; then
          echo "Version number in pyproject.toml does not match PR title"
          exit 1
        fi
        if [[ "${{ steps.check-tag.outputs.exists }}" != 'true' ]]; then
          echo "Version number already belongs to an existing tag, if that release is not a draft this will do nothing."
        fi
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "erebus.zip"
        body: ${{ github.event.pull_request.body }}
        tag: ${{ github.event.pull_request.title }}
        name: Version ${{ github.event.pull_request.title }}
        draft: true
        updateOnlyUnreleased: true
        allowUpdates: true
