name: Publish dev artifact
on: 
  push:
    branches-ignore:
      - 'gh-pages'
    paths:
      - src/**
  workflow_dispatch:

jobs:
  build_package:
    uses: ./.github/workflows/build_package.yaml
